# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/project_1.runs/synth_1/parallel_ber_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 16
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/project_1.cache/wt [current_project]
set_property parent.project_path /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_repo_paths /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS [current_project]
update_ip_catalog
set_property ip_output_repo /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/noise15dB.mem
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/test_patterns.mem
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/syndrome_lut.mem
}
read_verilog -library xil_defaultlib -sv {
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/PAM_4.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/berlekamp.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/channel_model.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/chien-search.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/convolutional_interleaver.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/decode.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/encode.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/epf_channel.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/inverse.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/noise.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/parallel_to_serial.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/prbs.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/rs_1d.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/rs_decode_wrapper.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/rs_encode_wrapper.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/serial_to_parallel.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/slicer.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/sova.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/sova_modules.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/rs/syndrome.sv
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/ber_top.sv
}
read_verilog -library xil_defaultlib {
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/grey_code.v
  /autofs/fs1.ece/fs1.eecg.tcc/liqasim1/Desktop/projects/s25-uoft-ri-fpga/BER_SIM_ZCU102/BER_IP/FULL_1D_RS/code/precode.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top parallel_ber_top -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef parallel_ber_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file parallel_ber_top_utilization_synth.rpt -pb parallel_ber_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
